stages:
  - build
  - test

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
  policy: pull

pre_install:
  stage: .pre
  script:
    - npm ci --cache .npm --prefer-offline

  cache:
    key: 
      files:
        - package-lock.json
    paths:
    - node_modules/
    when: on_success
    policy: pull-push

install_dependencies:
  image: node:latest
  stage: build
  script: 
    - npm run build
    # - npm run type:check
    - echo "Build successful"

run_tests:
  stage: test
  needs:
    - job: install_dependencies
      artifacts: true 
  script: npm test
