# Build and test the backend of the project
# Author: Vasile Grigoras (PSYVG1)

stages:
  - Build-Backend
  - Test-Backend

# Build and test the project
Build-Backend:
  image: node:14
  stage: Build-Backend
  script: 
    - cd ./backend
    - npm ci --silent
    - echo "Build successful"
  cache:
    key: "$CI_COMMIT_SHA"
    policy: push
    paths:
      - backend/node_modules/
  artifacts:
    paths:
      - backend/node_modules/
    expire_in: 1 week

Test-Backend:
  stage: Test-Backend
  needs:
    - job: Build-Backend
      artifacts: true 
  script: npm run test
