image: node:latest

stages:
  - build
  - test

install_dependencies:
  stage: build
  script: 
    - npm install
    - npm i react-scripts
    # - npm run type:check
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

run_tests:
  stage: test
  needs:
    - install_dependencies
  script: npm run test

