image: node:latest

stages:
  - build
  - test

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
  policy: pull

script:
  - npm ci --cache .npm --prefer-offline

install_dependencies:
  stage: build
  script: 
    - npm install
    # - npm run type:check
    - echo "Build successful"

  # artifacts:
  #   expire_in: 1 hour
  #   paths:
  #     - node_modules/
  #     - build

run_tests:
  stage: test
  needs:
    - install_dependencies
  script: npm test

